euroc = {1: ['/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s1_b_0/predictions',
             '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s1_b_1/predictions',
             '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s1_b_2/predictions',
             '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s1_b_3/predictions',
             '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s1_b_4/predictions'],
         2: ['/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s2_b_0/predictions',
             '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s2_b_1/predictions',
             '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s2_b_2/predictions',
             '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s2_b_3/predictions',
             '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s2_b_4/predictions'],
         3: ['/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s3_b_0/predictions',
             '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s3_b_1/predictions',
             '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s3_b_2/predictions',
             '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s3_b_3/predictions',
             '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s4_b_4/predictions'],
         4: ['/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s4_b_0/predictions',
             '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s4_b_1/predictions',
             '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s4_b_2/predictions',
             '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s4_b_3/predictions',
             '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s4_b_4/predictions'],
         'loops': ['/dbstore/datasets/robotics/mlflow/odometry/artifacts/euroc_x_bovw_sintel_g/8c399ae305444513b1e6e5cd13ce4040/artifacts/flexible2_b_0/predictions',
                   '/dbstore/datasets/robotics/mlflow/odometry/artifacts/euroc_x_bovw_sintel_g/f8fd71b43a73419087f493f127bcee9d/artifacts/flexible2_b_2/predictions',
                   '/dbstore/datasets/robotics/mlflow/odometry/artifacts/euroc_x_bovw_sintel_g/4d7d7f5370ae4e509fb91a89ac5bc5f7/artifacts/flexible2_b_3/predictions',
                   '/dbstore/datasets/robotics/mlflow/odometry/artifacts/euroc_x_bovw_sintel_g/132e907240c549868abf3b0a20c2fe38/artifacts/flexible2_b_1/predictions',
                   '/dbstore/datasets/robotics/mlflow/odometry/artifacts/euroc_x_bovw_sintel_g/73bdedb451db440a9be5af8cd1e6b970/artifacts/flexible2_b_4/predictions']
         }

euroc_clr = {1: ['/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s1_b_0/predictions',
                 '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s1_b_1/predictions',
                 '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s1_b_2/predictions',
                 '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s1_b_3/predictions',
                 '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s1_b_4/predictions'],
             2: ['/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s2_b_0/predictions',
                 '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s2_b_1/predictions',
                 '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s2_b_2/predictions',
                 '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s2_b_3/predictions',
                 '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s2_b_4/predictions'],
             3: ['/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s3_b_0/predictions',
                 '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s3_b_1/predictions',
                 '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s3_b_2/predictions',
                 '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s3_b_3/predictions',
                 '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s4_b_4/predictions'],
             4: ['/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s4_b_0/predictions',
                 '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s4_b_1/predictions',
                 '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s4_b_2/predictions',
                 '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s4_b_3/predictions',
                 '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_clr_s4_b_4/predictions'],
             'loops': ['/dbstore/datasets/robotics/mlflow/odometry/artifacts/euroc_x_bovw_sintel_g/7d0e8d8e71be4aeda4f1905240c9f038/artifacts/flexible2_clr_b_0/predictions',
                       '/dbstore/datasets/robotics/mlflow/odometry/artifacts/euroc_x_bovw_sintel_g/df2d07b531684ae1aff298eb96bda1f3/artifacts/flexible2_clr_b_3/predictions',
                       '/dbstore/datasets/robotics/mlflow/odometry/artifacts/euroc_x_bovw_sintel_g/3b41d33bb45441fd8a64a5a51a00764d/artifacts/flexible2_clr_b_1/predictions',
                       '/dbstore/datasets/robotics/mlflow/odometry/artifacts/euroc_x_bovw_sintel_g/49b3118a87bb43119338886b3aced735/artifacts/flexible2_clr_b_2/predictions',
                       ' /dbstore/datasets/robotics/mlflow/odometry/artifacts/euroc_x_bovw_sintel_g/2efb079b52864f36aa6fb54b19f73d3a/artifacts/flexible2_clr_b_4/predictions']
             }

euroc_mn = {1: ['/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s1_mn_b_0/predictions',
                '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s1_mn_b_1/predictions',
                '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s1_mn_b_2/predictions',
                '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s1_mn_b_3/predictions',
                '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s1_mn_b_4/predictions'],
            2: ['/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s2_mn_b_0/predictions',
                '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s2_mn_b_1/predictions',
                '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s2_mn_b_2/predictions',
                '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s2_mn_b_3/predictions',
                '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s2_mn_b_4/predictions'],
            3: ['/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s3_mn_b_0/predictions',
                '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s3_mn_b_1/predictions',
                '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s3_mn_b_2/predictions',
                '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s3_mn_b_3/predictions',
                '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s4_mn_b_4/predictions'],
            4: ['/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s4_mn_b_0/predictions',
                '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s4_mn_b_1/predictions',
                '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s4_mn_b_2/predictions',
                '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s4_mn_b_3/predictions',
                '/Vol0/user/d.zhukov/Projects/odometry/experiments/euroc_x_sintel_g/flexible2_s4_mn_b_4/predictions'],
            'loops': ['/dbstore/datasets/robotics/mlflow/odometry/artifacts/euroc_x_bovw_sintel_g/082a48b2a1e84d20b259e476339f1365/artifacts/flexible2_mn_b_1/predictions',
                      '/dbstore/datasets/robotics/mlflow/odometry/artifacts/euroc_x_bovw_sintel_g/c969ceafdfd140a8bc03cdff4f063b9c/artifacts/flexible2_mn_b_0/predictions',
                      '/dbstore/datasets/robotics/mlflow/odometry/artifacts/euroc_x_bovw_sintel_g/a3ffbb74d7a24053b5ce9717add856e4/artifacts/flexible2_mn_b_2/predictions',
                      '/dbstore/datasets/robotics/mlflow/odometry/artifacts/euroc_x_bovw_sintel_g/9cb45c441a004a8eb14ecb2790b20388/artifacts/flexible2_mn_b_3/predictions',
                      '/dbstore/datasets/robotics/mlflow/odometry/artifacts/euroc_x_bovw_sintel_g/9d5e7ab69a2146faa24b6bf0396c9fc7/artifacts/flexible2_mn_b_4/predictions']
            }